### ISSUE TITLE
Returning wrong result when rendering markdown list syntax

### ISSUE THREAD

**Issue by sjstyle** [cerebral/marksy#1]
Hi. I'm testing 'marksy' for using at my project. But I get wrong result when rendering markdown list syntax.

### Test sample

- Colors
    - Red
    - Blue
- Shape
  - Triangle
  - Rectangle

### What I wanted

![image](https://cloud.githubusercontent.com/assets/4811664/25085719/8c581bdc-239e-11e7-8500-f9f7428e285f.png)

### What I actually get

![image](https://cloud.githubusercontent.com/assets/4811664/25085678/60aedf52-239e-11e7-8f6e-86100739743a.png)

**Comment by christianalfoni** [comment]
@sjstyle Hi and thanks for the feedback! I am currently working on this branch: https://github.com/cerebral/marksy/tree/rewriteWithSnapshotTests with a rewrite and JEST tests. These things will be a lot easier to identify and fix. I hope to get it done as soon as possible, but still some more work to do there :)

**Comment by sjstyle** [comment]
@christianalfoni 
I solved that issue by changing `render.list` function like :
``` javascript
  renderer.list = function (body, ordered) {
    var id = inlineIds++;
    inlines[id] = React.createElement(ordered ? options.ol || 'ol' : options.ul || 'ul', {key: keys++}, createBlockContent(body));

    (inlines[id].props.children).map(function(item) {
      if (item && (item.type === 'li' || item.type === 'ul')) {
        if (item.props && item.props.children) {
          item.props.children.map(function(inlineItem) {
            if (inlineItem) {
              result = result.filter(function (i) {
                return i.key !== inlineItem.key;
              });
            }
          });
        }
      }
    });
    result.push(inlines[id]);
    return '{{' + id + '}}';
  };
```

But, I think your 'rewriting' code will be better than my solution. :)

**Comment by christianalfoni** [comment]
@sjstyle Thanks for the tip! Will keep it in mind with rewrite :-D

**Comment by christianalfoni** [comment]
I can confirm this is fixed in next version :-)

**Comment by sjstyle** [comment]
Thanks for pinging. I'm looking forward to see next version!

**Comment by christianalfoni** [comment]
It is out now :-)
