### ISSUE TITLE
Issue when using braces inside custom component

### ISSUE THREAD

**Issue by kirill-kruchkov** [cerebral/marksy#15]
When using braces inside custom component the component's node doesn't render at all to the top custom component inclusive.

![screen shot 2017-06-09 at 18 56 33](https://user-images.githubusercontent.com/1702672/26983830-c57e1d00-4d45-11e7-9b49-efd4923e68bb.png)
![screen shot 2017-06-09 at 18 56 38](https://user-images.githubusercontent.com/1702672/26983834-c8c1ecbc-4d45-11e7-90aa-b4504f9073a2.png)

**Comment by christianalfoni** [comment]
Hi there!

This is interesting. The demo runs with `marksy/components`. meaning that all HTML is transpiled by babel. the `{` in components world is actually syntax, causing it to be invalid when there is only one. Example:

```js
function ({bar}) {
  return <div>foo {bar}</div>
}
```

You have to think of it as React code :-)

So your example should work if you:

```js
<Row>
  <Col>{`Need to tell you something over here
.my-class {
`}</Col>
</Row>
```

**Comment by kirill-kruchkov** [comment]
@christianalfoni, got it. Thank you!
