### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by bgazzera** [cerebral/marksy#16]
Hi there!
I was trying to follow the instructions to install from source, but I think there are a couple of things missing.
After cloning and npm installing, the initial build failed. So I added babel-cli to the devDependencies and highlight.js to the dependencies. 
That got the build going.
But then npm start showed a blank page, I saw an error msg in the console, so I added createElement to the options object in /app/main.js

```
import React, {createElement} from 'react'
...

const compile = marksy({
  highlight: hljs,
  createElement,
  components: {
  ...
})
```
If you want I can do a PR with this. And maybe also update the README

Cheers!

**Comment by christianalfoni** [comment]
Hi man, thanks for feedback :-)

I have fixed error and updated deps now!
