### ISSUE TITLE
Custom components aren't being assigned a key

### ISSUE THREAD

**Issue by deadlybutter** [cerebral/marksy#2]
Markup is being applied to the page, but React is complaining it doesn't have a key,

![screen shot 2017-04-29 at 6 53 29 pm](https://cloud.githubusercontent.com/assets/897368/25559645/2da3354a-2d0d-11e7-9bf1-b85bfbbc3a78.png)

This error only occurs when the custom component is on the page

**Comment by christianalfoni** [comment]
This is fixed in new version about to arrive :)

**Comment by christianalfoni** [comment]
Next version is out :)

**Comment by deadlybutter** [comment]
@christianalfoni awesome, I look forward to trying it out soon!
