### ISSUE TITLE
Render elements without wrapper div when using marksy/components

### ISSUE THREAD

**Issue by astrotim** [cerebral/marksy#30]
When rendering the markdown via `marksy/components`, I can see each element is returned inside the `<HtmlWrapper>` component, which outputs a parent `<div>` with everything inside as children. Is there any way to render the elements without the wrapper div? I am using a custom component for a blockquote, hence my use of the 'components` feature.

**Comment by christianalfoni** [comment]
@astrotim This was actually to fix a bug related to component re-rendering, but diving into it again it does not really make sense... maybe I fixed it in a different way. Removed it now in 5.0.0 :-)

**Comment by astrotim** [comment]
Legend 👍
