### ISSUE TITLE
code and codespan elements

### ISSUE THREAD

**Issue by UsulPro** [cerebral/marksy#38]
Hi! Thank you for this project!

I tried to override `code` and `codespan` elements and found out only this workaround:

```js
const compile = marksy({
  createElement: React.createElement,
  highlight(language, code) {
    return hljs.highlight(language, code).value;
  },
  elements: {
    code({ language, children, code }) {
      return (
        children ? // render inline code:
          <code>
            {children}
          </code> : // render block code:
        <div>
          <span>
          language: {language}
          </span>
          <pre>
            <code>
              {code}
            </code>
          </pre>
        </div>
      );
    },
  },
})
```

Is it intended behavior and maybe it worth to update readme in this case?

**Comment by christianalfoni** [comment]
@UsulPro Sorry for very late response here. You mean to handle inline and block code? Yeah, not tried it, but makes sense to do it like this. Maybe you want to create a PR for it? :)

**Comment by Hypnosphi** [comment]
I believe this isn't fixed: `renderer.code` doesn't use `addElement`, so there's actually no way to override it via options
https://github.com/cerebral/marksy/blob/master/src/createRenderer.js#L52-L67

**Comment by Hypnosphi** [comment]
Now, when I look to the tests, I see that there's one for "components" version, but none for "default" version. So is there a chance that this intentionally doesn't work in "default"?

https://github.com/storybooks/marksy/blob/master/src/index.test.js#L383

**Comment by Hypnosphi** [comment]
Bu the way, looks like `codespan` element is never actually used (`renderer.codespan` uses `code`)
