### ISSUE TITLE
custom components and indentation

### ISSUE THREAD

**Issue by revolunet** [cerebral/marksy#39]
Hi, playing with marksy to mix markdown + react components

Looks like components are not renderer if they are indented

this works 

```js
const md = `
  # hello

  <MyCustomComponent>blablala</MyCustomComponent>
`;
```

this don't :

```js
const md = `
  # hello

    <MyCustomComponent>blablala</MyCustomComponent>
`;
```

MyCustomComponent has 2 more leading spaces :)

**Comment by christianalfoni** [comment]
@revolunet Aha, interesting! This is highly likely to markdown parsing. If you rather do:

```js
const md = `
  # hello

  ```marksy
    <MyCustomComponent>blablala</MyCustomComponent>
  ```
`;
```

You should be able to do whatever :)

**Comment by christianalfoni** [comment]
Just closing this as there is no response
