### ISSUE TITLE
How to make marksy support extensions?

### ISSUE THREAD

**Issue by nachiket-p** [cerebral/marksy#40]
How to use marksy for custom extensions?
e.g wants to generate forms (with react components), using (or similar to) https://github.com/jldec/marked-forms
Is this possible with Marksy?

**Comment by christianalfoni** [comment]
@nachiket-p Not in the same way. `marksy` does not extend the markdown syntax, it just allows you to write React syntax in your markdown. So you would just add all your components to marksy and then use them directly in the markdown :)

```js
marksy({
  components: {
    Form,
    Input // etc.
  }
})
```
