### ISSUE TITLE
How to render dom to the page?

### ISSUE THREAD

**Issue by motleydev** [cerebral/marksy#6]
Sorry for what may be an obvious question - and it may be related to some config setting in react-red-box as that's what's throwing the error. I have a markdown file that I am rendering out to the page. I then dump the tree directly into my render function (surrounded by a parent node) - I actually get a flash of correctly rendered DOM and then red-box throws an error about objects not being valid components.

**This is an example of my tree output:**
```
[{"type":"h1","key":"0","ref":null,"props":{"children":["Welcome to the jungle"]},"_owner":null,"_store":{}}
```

**And this is my error:**
```
Objects are not valid as a React child (found: object with keys {type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `_class`.
```

**Comment by motleydev** [comment]
Could it be that this is missing from the tree method?

https://facebook.github.io/react/blog/2015/12/18/react-components-elements-and-instances.html#further-reading
> All React elements require an additional $$typeof: Symbol.for('react.element') field declared on the object for security reasons. It is omitted in the examples above. This blog entry uses inline objects for elements to give you an idea of what’s happening underneath but the code won’t run as is unless you either add $$typeof to the elements, or change the code to use React.createElement() or JSX. ↩

**Comment by christianalfoni** [comment]
@motleydev Hm, this seems weird. Does it work without using the react-red-box plugin thingy? I have not tried that.

**Comment by christianalfoni** [comment]
Closing this as it is getting old, reopen if you want :)

**Comment by srosset81** [comment]
I'm getting the same error message.

`Objects are not valid as a React child (found: object with keys {tree, toc}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of styled.span.`

**Comment by christianalfoni** [comment]
@srosset81 You have to render `compile('# hey').tree`, not just `compile` :)

**Comment by srosset81** [comment]
Ah ok, thanks !
