### ISSUE TITLE
default element overrides don't work?

### ISSUE THREAD

**Issue by aeroheim** [cerebral/marksy#8]
Hi! I ran a very simple example below and the results aren't what I expected:
```js
const compile = marksy({
    h1(props) { return <h1>bar</h1> },
})

const compiled = compile('# foo');

console.log(compiled.tree) // <h1> element inside contains children 'foo' instead of 'bar'
```
Perhaps I'm not using marksy correctly. Is this working as intended?

**Comment by christianalfoni** [comment]
Hi @aeroheim and thanks for reporting! I just released a new version where this is fixed. It seems my refactor and tests did not cover this, embarrassing :-)

A new breaking version is also being published tomorrow to optimize use of the new `components` feature... just to give you a heads up. Project follows semver so will be major version update on that release.

**Comment by aeroheim** [comment]
@christianalfoni I just tried out the new release and everything is working as expected. Thanks for addressing this so quickly!
